const ProjSupp = [
  {
    id: "1",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "آشغالگیر مکانیکی دهانه درشت",
    compan: "SERECO - ITALY",
  },
  {
    id: "2",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "آشغالگیر مکانیکی دهانه ریز",
    compan: "SERECO - ITALY",
  },
  {
    id: "3",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "کلاسیفایر شستشوی دانه",
    compan: "SERECO - ITALY",
  },
  {
    id: "4",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "اسکروپمپ",
    compan: "REHART -  GERMANY",
  },
  {
    id: "5",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "دیفیوزر هوادهی",
    compan: "EDI - USA",
  },
  {
    id: "6",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "بلوئر دانه گیری",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "7",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "بلوئر هوادهی",
    compan: "NEXT TURBO - ITALY",
  },
  {
    id: "8",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "پمپ های مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "9",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "خردکن لجن",
    compan: "SEEPEX - GERMANY",
  },
  {
    id: "10",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "میکسرهای مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "11",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "دستگاه تغلیظ مکانیکی و آبگیری مکانیکی لجن",
    compan: "ANDRITZ - FRANCE",
  },
  {
    id: "12",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "پکیج تهیه محلول مواد شیمیایی",
    compan: "PROMINET - GERMANY",
  },
  {
    id: "13",
    idProj: "3",
    name: " تصفیه خانه فاضلاب شهر تبریز",
    employer: "شرکت آب و فاضلاب آذربایجان شرقی",
    consultant: " شرکت مهندسین مشاور فرازآب",
    materiel: "پمپ های هلیکال روتور",
    compan: "SEEPEX - GERMANY",
  },
  {
    id: "14",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "آشغالگیر مکانیکی دهانه درشت",
    compan: "EMO - GERMANY",
  },
  {
    id: "15",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "آشغالگیر مکانیکی دهانه ریز",
    compan: "EMO - GERMANY",
  },
  {
    id: "16",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "کلاسیفایر دانه",
    compan: "EMO - GERMANY",
  },
  {
    id: "17",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "کامپکتور آشغال",
    compan: "EMO - GERMANY",
  },
  {
    id: "18",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "کانوایر آشغال",
    compan: "EMO - GERMANY",
  },
  {
    id: "19",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "بلوئر دانه گیر  ",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "20",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "بلوئر هوادهی ",
    compan: "NEXT TURBO - ITALY",
  },
  {
    id: "21",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "میکسر مستغرق ",
    compan: "KSB - GERMANY",
  },
  {
    id: "22",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "پمپهای لجن ",
    compan: "KSB - GERMANY",
  },
  {
    id: "23",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "دیفیوزر هوادهی",
    compan: "KSB - GERMANY",
  },
  {
    id: "24",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS - GERMANY",
  },
  {
    id: "25",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "گیربکس",
    compan: "NORD - GERMANY",
  },
  {
    id: "26",
    idProj: "4",
    name: " تصفیه خانه فاضلاب تهران مدول 7و8",
    employer: "شرکت فاضلاب تهران",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "وکیوم پمپ",
    compan: "EUROVACUUM - NETHERLANDS",
  },
  {
    id: "27",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "میکرو فیلتر (میکرو استرینر)",
    compan: "NORDIC WATER - SWEDEN",
  },
  {
    id: "28",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS-   GERMANY",
  },
  {
    id: "29",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "دستگاه سانتریفیوژ آبگیری لجن",
    compan: "ANDRITZ - FRANCE",
  },
  {
    id: "30",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "پمپ هلیکال روتور",
    compan: "SEEPEX  -GERMANY",
  },
  {
    id: "31",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "الکتروپمپ های سانتریفیوژ",
    compan: "KSB - GERMANY",
  },
  {
    id: "32",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "پکیج تزریق مواد شیمیایی",
    compan: "GRUNDFOS - DENMARK",
  },
  {
    id: "33",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "بلوئرهای هوادهی و بک واش فیلتر ",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "34",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "دیفیوزرهای هوادهی",
    compan: "EDI - USA ",
  },
  {
    id: "35",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "گیربکس",
    compan: "NORD - GERMANY",
  },
  {
    id: "36",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "الکتروموتور",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "37",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "مرکز دوران پلهای لجن",
    compan: "ROTHE ERDE - GERMANY",
  },
  {
    id: "38",
    idProj: "6",
    name: " تصفیه خانه آب شهر ساری",
    employer: "شرکت آب منطقه ای مازندران ",
    consultant: "شرکت مهندسین مشاور مهاب قدس",
    materiel: "تجهیزات کنترل و ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "39",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "میکرو فیلتر (میکرو استرینر )",
    compan: "TE - GERMANY",
  },
  {
    id: "40",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "اشغالگیر مکانیکی ",
    compan: "KUHN - GERMANY",
  },
  {
    id: "41",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "سیستم ضدعفونی توسط هیپوکلریت سدیم ",
    compan: "SEVERN TRENT  -USA",
  },
  {
    id: "42",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "دستگاه بلت تیکنر ",
    compan: "ANDRITZ - FRANCE",
  },
  {
    id: "43",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "پمپ هلیکال روتور ",
    compan: "NETZSCH -  GERMANY",
  },
  {
    id: "44",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "پکیج تزریق مواد شیمیایی ",
    compan: "MILTONROY – FRANCE,  ALLDOS - GERMANY",
  },
  {
    id: "45",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "بلوئرهای هوادهی  ",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "46",
    idProj: "1",
    name: " تصفیه خانه آب شهر بم",
    employer: "شرکت آب منطقه ای کرمان",
    consultant: "شرکت مهندسین مشاورطوس آب",
    materiel: "تجهیزات کنترل و ابزار دقیق  ",
    compan: "E&H - GERMANY",
  },
  {
    id: "47",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "دستگاه بلت تیکنر و بلت فیلترپرس",
    compan: "ANDRITZ - FRANCE",
  },
  {
    id: "48",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "الکتروپمپ های مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "49",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "میکسرهایی مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "50",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "الکتروموتورها",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "51",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "دیفیوزرهای هوادهی",
    compan: "EDI - USA",
  },
  {
    id: "52",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "بلوئرهای هوادهی",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "53",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "تجهیزات کنترل و ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "54",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS - GERMANY",
  },
  {
    id: "55",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "خردکن لجن",
    compan: "SEEPEX - GERMANY",
  },
  {
    id: "56",
    idProj: "5",
    name: " تصفیه خانه فاضلاب شهر واوان ",
    employer: "شرکت آب و فاضلاب جنوب غرب استان تهران ",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "پمپ هلیکال روتور",
    compan: "SEEPEX - GERMANY",
  },
  {
    id: "57",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی ",
    consultant: "شرکت مهندسین سازه",
    materiel: "الکتروپمپ های مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "58",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "میکسرهای مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "59",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "پمپ های هلیکال روتور",
    compan: "NETZSCH - GERMANY",
  },
  {
    id: "60",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "الکتروموتور",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "61",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "دیفیوزرهای هوادهی",
    compan: "EDI - USA",
  },
  {
    id: "62",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "بلوئرهای هوادهی",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "63",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "پکیج تزریق مواد شیمیایی",
    compan: "MILTORNROY - FRANCE",
  },
  {
    id: "64",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "دستگاه سانتریفیوژ آبگیری",
    compan: "ANDRITZ - FRANCE",
  },
  {
    id: "65",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "شیرآلات برقی",
    compan: "VACTRA - ITALY",
  },
  {
    id: "66",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "گیربکس",
    compan: "NORD - GERMANY",
  },
  {
    id: "67",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "مرکز دوران پل های لجن",
    compan: "ROTHE ERDE - GERMANY",
  },
  {
    id: "68",
    idProj: "25",
    name: " تصفیه خانه فاضلاب مجتمع پتروشیمی مبین",
    employer: "شرکت مبین پتروشیمی",
    consultant: "شرکت مهندسین سازه",
    materiel: "ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "69",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "میکروفیلتر (میکرواسترینر )",
    compan: "TE - GERMANY",
  },
  {
    id: "70",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "سیستم ضدعفونی با اشعه ماوراء بنفش",
    compan: "UV - OZONIA",
  },
  {
    id: "71",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "اسکروپمپ",
    compan: "RITZ ATRO - GERMANY",
  },
  {
    id: "72",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "دستگاه بلت تیکنر",
    compan: "TE - GERMANY",
  },
  {
    id: "73",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "دستگاه سانتریفیوژ آبگیری لجن",
    compan: "HAUS - TURKEY",
  },
  {
    id: "74",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "الکتروپمپ های مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "75",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "میکسر مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "76",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "پمپ هلیکال روتور",
    compan: "NETZSCH - GERMANY",
  },
  {
    id: "77",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "الکتروموتور",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "78",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "دیفیوزرهای هوادهی",
    compan: "EDI - USA",
  },
  {
    id: "79",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "بلوئرهای هوادهی",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "80",
    idProj: "14",
    name: " تصفیه خانه فاضلاب شهر بهارستان",
    employer: "شرکت آب و فاضلاب بهارستان اصفهان",
    consultant: "شرکت مهندسین مشاور طرح و تحقیقات آب  و فاضلاب ",
    materiel: "تجهیزات کنترل و ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "81",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "الکتروپمپ های مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "82",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "میکسرهای مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "83",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "الکتروموتور",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "84",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "جریان ساز",
    compan: "GRUNDFOS - DENMARK",
  },
  {
    id: "85",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "دیفیوزرهای هوادهی",
    compan: "EDI - USA",
  },
  {
    id: "86",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "بلوئرهای هوادهی",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "87",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "گیربکس",
    compan: "NORD - GERMANY",
  },
  {
    id: "88",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "مرکز دوران پلهای لجن",
    compan: "ROTHE ERDE - GERMANY",
  },
  {
    id: "89",
    idProj: "9",
    name: " تصفیه خانه فاضلاب شهر رودان ",
    employer: "شرکت آب و فاضلاب استان هرمزگان",
    consultant: "شرکت مهندسین مشاور پارس آب تدبیر",
    materiel: "تجهیزات کنترل و ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "90",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "الکتروهای پمپ های مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "91",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "میکسرهای مستغرق",
    compan: "KSB - GERMANY",
  },
  {
    id: "92",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "الکتروموتور",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "93",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "دیفیوزرهای هوادهی",
    compan: "EDI - USA",
  },
  {
    id: "94",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "بلوئرهای هوادهی",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "95",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS - GERMANY",
  },
  {
    id: "96",
    idProj: "8",
    name: " تصفیه خانه فاضلاب شهر محمود آباد",
    employer: "شرکت آب و فاضلاب استان قزوین",
    consultant: "شرکت مهندسین مشاور آرنا",
    materiel: "ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "97",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    employer: "شرکت آب منطقه ای آذربایجان شرقی",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "پکیج تزریق مواد شیمیایی",
    compan: "MILTONROY - FRANCE",
  },
  {
    id: "98",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    employer: "شرکت آب منطقه ای آذربایجان شرقی",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "محرک برقی شیرآلات",
    compan: "AUMA - GERMANY",
  },
  {
    id: "99",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    employer: "شرکت آب منطقه ای آذربایجان شرقی",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS - GERMANY",
  },
  {
    id: "100",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    employer: "شرکت آب منطقه ای آذربایجان شرقی",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "بلوئر بکواش فیلتر",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "101",
    idProj: "2",
    name: " تصفیه خانه آب شهر میانه",
    employer: "شرکت آب منطقه ای آذربایجان شرقی",
    consultant: "شرکت مهندسین مشاور آبران",
    materiel: "تجهیزات کنترل و ابزار دقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "102",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقه ای آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    materiel: "پکیج تزریق مواد شیمیایی",
    compan: "MILTONROY - FRANCE",
  },
  {
    id: "103",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقه ای آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    materiel: "وکیوم پمپ پولساتور",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "104",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقه ای آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS - GERMANY",
  },
  {
    id: "105",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقهای  آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    materiel: "میکسرهای شیمیایی",
    compan: "MILTONROY - FRANCE",
  },
  {
    id: "106",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقه ای آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    materiel: "بلوئر بکواش فیلتر",
    compan: "AERZEN - GERMANY",
  },
  {
    id: "107",
    idProj: "18",
    name: " تصفیه خانه آب شهر تکاب",
    employer: "شرکت سهامی آب منطقه ای آذربایجان غربی ",
    consultant: "شرکت مهندسین مشاور آشناب",
    materiel: "شیرهای پینچ",
    compan: "MILTONROY - FRANCE",
  },
  {
    id: "108",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز",
    employer: "شرکت آب و فاضلاب گلستان",
    consultant: "شرکت مهندسین مشاور پژوهاب",
    materiel: "سیستم کلرزنی",
    compan: "JESCO - GERMANY",
  },
  {
    id: "109",
    idProj: "20",
    name: " تصفیه خانه فاضلاب شهر بندر گز",
    employer: "شرکت آب و فاضلاب گلستان",
    consultant: "شرکت مهندسین مشاور پژوهاب",
    materiel: "پمپ های مستغرق",
    compan: "FLYGT - SWEDEN",
  },
  {
    id: "110",
    idProj: "21",
    name: " تصفیه خانه فاضلاب دزفول",
    employer: "شرکت آب و فاضلاب استان خوزستان",
    consultant: "شرکت مهندسین مشاور ری آب",
    materiel: "سیستم کلرزنی",
    compan: "ALLDOS - GERMANY",
  },
  {
    id: "111",
    idProj: "21",
    name: " تصفیه خانه فاضلاب دزفول",
    employer: "شرکت آب و فاضلاب استان خوزستان",
    consultant: "شرکت مهندسین مشاور ری آب",
    materiel: "تجهیزات کنترل و ابزاردقیق",
    compan: "E&H - GERMANY",
  },
  {
    id: "112",
    idProj: "21",
    name: " تصفیه خانه فاضلاب دزفول",
    employer: "شرکت آب و فاضلاب استان خوزستان",
    consultant: "شرکت مهندسین مشاور ری آب",
    materiel: "الکتروموتور",
    compan: "SIEMENS - GERMANY",
  },
  {
    id: "113",
    idProj: "24",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    employer: "شرکت آب و فاضلاب گلستان",
    consultant: "شرکت مهندسین مشاور پژوهاب",
    materiel: "سیستم کلرزنی",
    compan: "JESCO - GERMANY",
  },
  {
    id: "114",
    idProj: "24",
    name: " تصفیه خانه فاضلاب شهر کردکوی",
    employer: "شرکت آب و فاضلاب گلستان",
    consultant: "شرکت مهندسین مشاور پژوهاب",
    materiel: "پمپ های مستغرق",
    compan: "FLYGT - SWEDEN",
  },
];

export { ProjSupp };
